#!/usr/bin/env bash
# Build the provider and write dev.terraform.rc next to this script (gitignored).
# Usage: from this directory: ./dev-setup.sh
# Then:  export TF_CLI_CONFIG_FILE="$(pwd)/dev.terraform.rc"
#        terraform validate && terraform plan

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROVIDER_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
BIN="${PROVIDER_ROOT}/terraform-provider-xui"
RC_OUT="${SCRIPT_DIR}/dev.terraform.rc"

echo "Building provider in ${PROVIDER_ROOT} ..."
(cd "${PROVIDER_ROOT}" && go build -o terraform-provider-xui .)

cat >"${RC_OUT}" <<EOF
# Generated by dev-setup.sh — do not commit (see .gitignore).
provider_installation {
  dev_overrides {
    "example.com/xui/xui" = "${PROVIDER_ROOT}"
  }
  direct {}
}
EOF

echo "Wrote ${RC_OUT}"
echo "Run from ${SCRIPT_DIR}:"
echo "  export TF_CLI_CONFIG_FILE=\"${RC_OUT}\""
echo "  terraform validate && terraform plan"
echo "Regenerate registry docs from ${PROVIDER_ROOT}:"
echo "  make -C \"${PROVIDER_ROOT}\" docs"
